[package]
name = "buidlland"
version = "1.0.0"
authors = []

[addresses]
buidlland = "0xbbe77a4bbb35fc09ccf594f9ee7963f5a34f067c6ae3105a8ad887c0fa865de8"
[dev-addresses]

[dependencies.EndlessFramework]
git = "https://github.com/endless-labs/endless-move-framework"
rev = "main"
subdir = "endless-framework"

[dev-dependencies]
