[package]
name = "buidlland"
version = "1.0.0"
authors = []

[addresses]
buidlland = "_"
[dev-addresses]

[dependencies.EndlessFramework]
git = "https://github.com/endless-labs/endless-move-framework"
rev = "main"
subdir = "endless-framework"

[dev-dependencies]
